import type { Metadata } from "next";
import "./globals.css";

//Components
import Fonts from "./components/Fonts";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { DarkLightProvider } from "./contexts/DarkLightContext";
import ThemeSwitcher from "./components/DarkLightSwitcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Fonts />
      </head>
      <body>
        <DarkLightProvider>
          <Header />
          <main className="main">{children}</main>
          <Footer />
        </DarkLightProvider>
      </body>
    </html>
  );
}
